---
- name: Development environment playbook.
  hosts: localhost
  vars_files:
    - config.yml

  pre_tasks:
    - name: Display system info.
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ansible_os_family = {{ ansible_os_family }}
        - ansible_distribution == {{ ansible_distribution }}
        - ansible_distribution_major_version == {{ ansible_distribution_major_version }}
        - ansible_architecture == {{ ansible_architecture }}
      tags:
        - always
    - name: Ensure certain directories exist.
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
      loop:
        - bin
        - install
      tags:
        - always

  tasks:
    - name: Install core packages.
      ansible.builtin.import_tasks: "tasks/core.yml"
      tags:
        - core

    - name: Install Python.
      ansible.builtin.import_role:
        name: python
      tags:
        - python

    - name: Install cargo.
      ansible.builtin.import_tasks: "tasks/cargo.yml"
      tags:
        - cargo

    - name: Install i3.
      ansible.builtin.import_tasks: "tasks/i3.yml"
      tags:
        - i3

    - name: Install texlive.
      ansible.builtin.import_tasks: "tasks/texlive.yml"
      tags:
        - tex

    - name: Install XFCE4.
      ansible.builtin.import_tasks: "tasks/xfce4.yml"
      tags:
        - xfce4

    - name: Install kitty.
      ansible.builtin.import_tasks: "tasks/kitty.yml"
      tags:
        - kitty

    - name: Install souffle.
      ansible.builtin.import_tasks: "tasks/souffle.yml"
      tags:
        - souffle
