---
- name: Development environment playbook.
  hosts: localhost
  vars_files:
    - config.yml
  connection: local

  pre_tasks:
    - name: Display system info.
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ansible_os_family = {{ ansible_os_family }}
        - ansible_distribution == {{ ansible_distribution }}
        - ansible_distribution_major_version ==
            {{ ansible_distribution_major_version }}
      tags:
        - always

    - name: Ensure certain directories exist.
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
        mode: 0777
      loop:
        - bin
        - install
      tags:
        - always

  roles:
    - role: neovim
      nvim_version: "{{ version.neovim }}"
      tags:
        - neovim

  tasks:
    - name: Install core packages.
      ansible.builtin.import_tasks: "tasks/core.yml"
      tags:
        - core

    - name: Install fonts.
      ansible.builtin.import_tasks: "tasks/fonts.yml"
      tags:
        - fonts

    - name: Install nvim.
      ansible.builtin.import_tasks: "tasks/nvim.yml"
      tags:
        - nvim

    - name: Install Python.
      ansible.builtin.import_role:
        name: python
      tags:
        - python

    - name: Install Go.
      ansible.builtin.import_tasks: "tasks/go.yml"
      tags:
        - go

    - name: Install cargo.
      ansible.builtin.import_tasks: "tasks/cargo.yml"
      tags:
        - cargo

    - name: Install starship.
      ansible.builtin.import_tasks: "tasks/starship.yml"
      tags:
        - starship

    - name: Install vivid.
      ansible.builtin.import_tasks: "tasks/vivid.yml"
      tags:
        - vivid

    - name: Install XFCE4.
      ansible.builtin.import_tasks: "tasks/xfce4.yml"
      tags:
        - xfce4

    - name: Install zsh.
      ansible.builtin.import_tasks: "tasks/zsh.yml"
      tags:
        - zsh
