---
- name: OL9 environment playbook
  hosts: localhost
  vars_files:
    - config.yml

  pre_tasks:
    - name: Display system info.
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ansible_os_family = {{ ansible_os_family }}
        - ansible_distribution == {{ ansible_distribution }}
        - ansible_distribution_major_version ==
            {{ ansible_distribution_major_version }}
      tags:
        - always

    - name: Debug
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - ansible_env.HOME
        - ansible_env.USER
      tags:
        - debug

    - name: Ensure certain directories exist.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: u=rwx,g=rx,o=r
      loop:
        - opt
        - dev/personal
      tags:
        - always

  tasks:
    - name: Install core dependencies
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - gcc
        - gcc-c++
        - git
        - htop
        - java-17-openjdk-devel
        - make
        - man
        - man-pages
        - netcat
        - podman
        - podman-docker
        - python3
        - python3.11
        - stow
        - tmux
        - tree
        - zsh

    - name: Install nvim
      ansible.builtin.import_tasks: "tasks/nvim.yml"
      tags:
        - nvim

    - name: Install sdkman
      ansible.builtin.shell:
        cmd: |
          curl -s "https://get.sdkman.io" | bash
        creates: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
      tags:
        - sdkman
