---
- name: OL9 environment playbook
  hosts: localhost
  vars_files:
    - config.yml
  pre_tasks:
    - name: Display system info.
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ansible_os_family = {{ ansible_os_family }}
        - ansible_distribution == {{ ansible_distribution }}
        - ansible_distribution_major_version == {{ ansible_distribution_major_version }}
      tags:
        - always
    - name: Debug
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - ansible_env.HOME
        - ansible_env.USER
      tags:
        - debug
    - name: Ensure certain directories exist.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: u=rwx,g=rx,o=r
      loop:
        - opt
        - dev/personal
      tags:
        - always
  tasks:
    - name: Install EPEL repo
      become: true
      ansible.builtin.dnf:
        name: oracle-epel-release-el9
        state: present
        update_cache: false
      tags:
        - epel
    - name: Install core dependencies
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        update_cache: false
      loop:
        - bzip2
        - cmake
        - fd-find
        - flatpak
        - fuse
        - fzf
        - gcc
        - gcc-c++
        - git
        - git-delta
        - htop
        - hyperfine
        - jq
        - make
        - man
        - man-pages
        - ncurses
        - podman
        - podman-docker
        - python3
        - python3.11
        - ripgrep
        - stow
        - tldr
        - tmux
        - tokei
        - tree
        - unzip
        - xclip
        - xz
        - zip
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      tags:
        - core
    - name: Install flatpak
      ansible.builtin.import_tasks: "tasks/flatpak.yml"
      tags:
        - flatpak
