---
- name: Development environment playbook.
  hosts: all
  vars_files:
    - config.yml
    - env.yml
  vars:
    integration_testing: false
  environment: "{{ env }}"

  gather_facts: true

  pre_tasks:
    - name: Display system info.
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ansible_os_family = {{ ansible_os_family }}
        - ansible_distribution == {{ ansible_distribution }}
        - ansible_distribution_major_version == {{ ansible_distribution_major_version }}
        - ansible_facts.kernel = {{ ansible_facts["kernel"] }}
        - ansible_facts.system_vendor = {{ ansible_facts["system_vendor"] }}
        - ansible_facts.virtualization_role = {{ ansible_facts["virtualization_role"] }}
      tags:
        - always

  roles:
    - role: preinstall
    - role: ubuntu_core
    - role: direnv
    - role: go
    - role: gocloc
    - role: lazygit
    - role: nvim
    - role: python
    - role: sdk
    - role: starship
    - role: nerd_fonts
      vars:
        nerd_fonts_fonts:
          - "ComicShannsMono"
          - "JetBrainsMono"
    - role: delta
    - role: hugo
    - role: hyperfine
    - role: pandoc
    - role: vivid
    - role: nvm
    - role: plan9

  tasks:
    - name: Install optional packages for host machine
      become: true
      ansible.builtin.apt:
        name:
          - pandoc
      when: '"WSL" not in ansible_facts["kernel"]'

    - name: Install optional packages for guest machine
      ansible.builtin.import_role:
        name: ubuntu_vbox
      when: '"WSL" not in ansible_facts["kernel"]'

    - name: Install wez
      ansible.builtin.import_role:
        name: wez
      when: >
        "WSL" not in ansible_facts["kernel"] or integration_testing
