---
- name: Remove previous installation
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/opt/hyperfine"
    - "/tmp/hyperfine"
    - "/tmp/hyperfine-x86_64-unknown-linux-gnu.tar.gz"
- name: Download release
  ansible.builtin.get_url:
    url: "https://github.com/sharkdp/hyperfine/releases/download/{{ hyperfine.release }}/hyperfine-{{ hyperfine.release }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/hyperfine-x86_64-unknown-linux-gnu.tar.gz"
    mode: u=rw,g=rw,o=r
- name: Create installation directory
  ansible.builtin.file:
    path: "/tmp/hyperfine"
    state: directory
    mode: u=rwx,g=rwx,o=rx
- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/hyperfine-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/hyperfine"
    remote_src: true
- name: Move installation to opt
  ansible.builtin.copy:
    src: "/tmp/hyperfine/hyperfine-{{ hyperfine.release }}-x86_64-unknown-linux-gnu"
    dest: "{{ ansible_env.HOME }}/opt"
    mode: u=rwx,g=rwx,o=rx
    remote_src: true
- name: Clean up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/hyperfine"
    - "/tmp/hyperfine-x86_64-unknown-linux-gnu.tar.gz"
- name: Add hyperfine to PATH
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.config/zsh/ansible.zsh"
    marker: "# {mark} HYPERFINE"
    block: |
      export PATH="$PATH:$HOME/opt/hyperfine-{{ hyperfine.release }}-x86_64-unknown-linux-gnu"
