---
- name: Install core dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - libX11-devel
    - libXt-devel
    - libXext-devel
    - fontconfig-devel
  when: ansible_os_family == 'RedHat'

- name: Install core dependencies
  become: true
  ansible.builtin.apt:
    name:
      - xorg-dev
  when: ansible_os_family == 'Debian'

- name: Download plan9port
  ansible.builtin.git:
    repo: https://github.com/9fans/plan9port.git
    dest: "{{ ansible_env.HOME }}/dev/personal/plan9/plan9port"
    version: be7c68f6954f7dcaa53403e0f600716f65a13d32
    update: false

- name: Download plan9go
  ansible.builtin.git:
    repo: git@github.com:nathanwn/9fans-go.git
    dest: "{{ ansible_env.HOME }}/dev/personal/plan9/go"
    version: f86105fb0728caf743246659b6ada899367a5cf7

- name: Download acme utilities by evbogdanov
  ansible.builtin.git:
    repo: https://github.com/evbogdanov/acme.git
    dest: "{{ ansible_env.HOME }}/dev/personal/plan9/evbogdanov"
    version: f8bc53de18541f69e578f25a552b23f0964e683b

- name: Build plan9port
  ansible.builtin.shell:
    chdir: "{{ ansible_env.HOME }}/dev/personal/plan9/plan9port"
    cmd: |
      ./INSTALL
    creates: "{{ ansible_env.HOME }}/dev/personal/plan9/plan9port/bin/acme"

- name: Build plan9go
  ansible.builtin.command:
    chdir: "{{ ansible_env.HOME }}/dev/personal/plan9/go"
    cmd: "make all"
    creates: "{{ ansible_env.HOME }}/dev/personal/plan9/go/bin/Watch"
