---
- name: Install core packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - curl
      - default-jdk
      - default-jre
      - htop
      - fd-find
      - firefox
      - fzf
      - pandoc
      - perl
      - python3-venv
      - python3-pip
      - stow
      - ripgrep
      - tmux
      - valgrind
      - wget
      - xclip
      - zathura
      - zsh
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
