---
- name: "cue - download tar"
  ansible.builtin.get_url:
    url: "https://github.com/cue-lang/cue/releases/download/v{{ cue.release }}/cue_v0.6.0_linux_amd64.tar.gz"
    dest: "/tmp/cue_v{{ cue.release }}_linux_amd64.tar.gz"
    checksum: "{{ cue.checksum }}"
    mode: u=rw,g=rw,o=r

- name: "cue - create installation directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/opt/cue"
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: "cue - extract tar"
  ansible.builtin.unarchive:
    src: "/tmp/cue_v{{ cue.release }}_linux_amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/opt/cue"
    remote_src: true  # source is on remote rather than local

- name: Remove tar
  ansible.builtin.file:
    path: "/tmp/cue_v{{ cue.release }}_linux_amd64.tar.gz"
    state: absent
