---
- name: Ensure fonts directory exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory
    mode: 0777

- name: Ensure directory for each font exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts/{{ item }}"
    state: directory
    mode: 0777
  loop: "{{ nerd_fonts.fonts }}"

- name: Install fonts.
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts.release }}/{{ item }}.zip"
    dest: "{{ ansible_env.HOME }}/.fonts/{{ item }}"
    remote_src: true
  loop: "{{ nerd_fonts.fonts }}"

- name: Reset font cache.
  ansible.builtin.command:
    cmd: fc-cache -rv
  changed_when: false  # TODO: improve this
