---
- name: Download kitty
  ansible.builtin.get_url:
    url: "https://github.com/kovidgoyal/kitty/releases/download/v{{ kitty.release }}/kitty-{{ kitty.release }}-x86_64.txz"
    dest: "{{ ansible_env.HOME }}/install"
    mode: u=rw,g=rw,o=r

- name: Ensure kitty directory exist.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin/kitty"
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Extract kitty
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/install/kitty-{{ kitty.release }}-x86_64.txz"
    dest: "{{ ansible_env.HOME }}/bin/kitty"
