---
- name: Download kitty
  ansible.builtin.get_url:
    url: "https://github.com/kovidgoyal/kitty/releases/download/v{{ kitty.release }}/kitty-{{ kitty.release }}-x86_64.txz"
    dest: "{{ ansible_env.HOME }}/install"
    mode: 0644

- name: Ensure kitty directory exist.
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/bin/kitty"
    state: directory
    mode: 0777

- name: Extract kitty
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/install/kitty-{{ kitty.release }}-x86_64.txz"
    dest: "{{ ansible_env.HOME }}/bin/kitty"
