---
- name: Add deadsnakes repository.
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:deadsnakes/ppa"


- name: Add pypi repository.
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:pypy/ppa"

- name: Install all Python versions that I need.
  become: true
  ansible.builtin.apt:
    name:
      - python3.8
      - python3.8-venv
      - python3.8-distutils
      - python3.9
      - python3.9-venv
      - python3.9-distutils
      - python3.10
      - python3.10-venv
      - python3.10-distutils
      - python3.11
      - python3.11-venv
      - python3.11-dev
      - python3.11-distutils
      - python3.12
      - python3.12-venv
      - python3.12-distutils
      - pypy3
    cache_valid_time: 3600
