---
- name: Install texlive.
  become: true
  ansible.builtin.apt:
    name:
      - latexmk
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-extra
    update_cache: true
    cache_valid_time: 3600
