---
- name: Install zsh-completions.
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/zsh-completions"
    version: "{{ zsh.plugins.zsh_completions.release }}"

- name: Install zsh-autosuggestions.
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/zsh-autosuggestions"
    version: "{{ zsh.plugins.zsh_autosuggestions.release }}"

- name: Install zsh-syntax-highlighting.
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/zsh-syntax-highlighting"
    version: "{{ zsh.plugins.zsh_syntax_highlighting.release }}"

- name: Install powerlevel10k.
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/powerlevel10k"
    version: "{{ zsh.plugins.powerlevel10k.release }}"
