---
- name: Download release
  ansible.builtin.get_url:
    url: "https://github.com/sharkdp/vivid/releases/download/v{{ vivid.release }}/vivid-v{{ vivid.release }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vivid-v{{ vivid.release }}-x86_64-unknown-linux-gnu.tar.gz"
    mode: u=rw,g=rw,o=r

- name: Create installation directory
  ansible.builtin.file:
    path: "/tmp/vivid"
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/vivid-v{{ vivid.release }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vivid"
    remote_src: true

- name: Move exec to opt
  ansible.builtin.copy:
    src: "/tmp/vivid/vivid-v{{ vivid.release }}-x86_64-unknown-linux-gnu/vivid"
    dest: "{{ ansible_env.HOME }}/opt/vivid"
    mode: u=rwx,g=rwx,o=rx
    remote_src: true

- name: Clean up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/vivid-v{{ vivid.release }}-x86_64-unknown-linux-gnu.tar.gz"
    - "/tmp/vivid"
