---
- name: Install dependencies (Oracle Linux).
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop:
    - autoconf
    - bluez-libs
    - bzip2-devel
    - expat-devel
    - libdb-devel
    - libffi-devel
    - libuuid-devel
    - gcc
    - gdbm-devel
    - glibc-devel
    - gnupg
    - gpm-devel
    - lcov
    - make
    - ncurses-devel
    - openssl-devel
    - pkgconfig
    - readline-devel
    - sqlite-devel
    - tk-devel
    - wget
    - xz
    - xz-devel
    - zlib-devel
