---
- name: Install xfce4 packages.
  become: true
  ansible.builtin.apt:
    name:
      - xdg-utils
      - xfce4
      - xfce4-clipman
      - xfce4-clipman-plugin
      - xfce4-cpufreq-plugin
      - xfce4-cpugraph-plugin
      - xfce4-dict
      - xfce4-diskperf-plugin
      - xfce4-fsguard-plugin
      - xfce4-genmon-plugin
      - xfce4-netload-plugin
      - xfce4-screenshooter
      - xfce4-systemload-plugin
      - xfce4-taskmanager
      - xfce4-terminal
      - xfce4-whiskermenu-plugin
      - xfce4-xkb-plugin
