---
- name: Remove previous installation
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/opt/hugo"
    - "/tmp/hugo"
    - "/tmp/hugo.tar.gz"

- name: Download release
  ansible.builtin.get_url:
    url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo.release }}/hugo_extended_{{ hugo.release }}_linux-amd64.tar.gz"
    dest: "/tmp/hugo.tar.gz"
    mode: u=rw,g=rw,o=r

- name: Create installation directory
  ansible.builtin.file:
    path: "/tmp/hugo"
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/hugo.tar.gz"
    dest: "/tmp/hugo"
    remote_src: true

- name: Move exec to opt
  ansible.builtin.copy:
    src: "/tmp/hugo/hugo"
    dest: "{{ ansible_env.HOME }}/opt/"
    mode: u=rwx,g=rwx,o=rx
    remote_src: true

- name: Clean up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/hugo.tar.gz"
    - "/tmp/hugo"
