---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - curl
      - fd-find
      - fuse
      - fzf
      - git
      - git-delta
      - htop
      - hyperfine
      - libfuse2
      - netcat-openbsd
      - perl
      - podman
      - podman-docker
      - python3-pip
      - python3-venv
      - ripgrep
      - stow
      - tldr
      - tmux
      - vivid
      - wget
      - xclip
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
