---
# tasks file for roles/neovim
- name: Install build prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    update_cache: true
    cache_valid_time: 3600

- name: Ensure install directory exists
  ansible.builtin.file:
    path: "{{ install_root_dir }}"
    state: directory
    mode: 0777

- name: Reset git tags
  ansible.builtin.command:
    chdir: "{{ install_dir }}"
    cmd: git fetch --tags -f
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Checkout version
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ install_dir }}"
    version: "{{ nvim_version }}"
  notify:
    - Remove previous build
    - Configure build
    - Install
